apiVersion: v1
kind: Service
metadata:
  name: deliveryservice-api
  namespace: deliverydomain
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: deliveryservice-api